<!DOCTYPE html>
<html>
<head>
  <title>{{$title}}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
  <div class="container">
    <div class="row">
    <div style="text-align: center;">
        <img src="{{public_path('logo/logo.png')}}" alt="logo" width="50" height="60">
        <h3>{{$title}}</h3>
    </div>
   
      <div class="col-lg-12" style="margin-top: 15px ">     
        
        <div class="pull-right">
          <h4>Month: {{$month}} Year: {{$year}}</h4>
        </div>
        <div class="pull-center">
          <p>As of: {{$date}}</p>
        </div>
      </div>
    </div><br>
    <table class="table table-bordered table-striped table-sm">
      <thead class="thead-dark">
        <th>#</th>
        <th>CERT NO</th>
        <th>Client Name</th>
        <th>Plate No.</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Policy Number</th>
        <th>Cover</th>
        <th>Amount</th>
       
        <th>Chasis No</th>
      </thead>
      @php
          $totalPremiumAmount = 0; // Initialize the variable to store the total premium amount
      @endphp
      @foreach ($results as $data)
      <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $data->refno }}</td>
        <td>{{ $data->client_names }}</td>
        <td>{{ $data->plate_number }}</td>
        <td>{{ \Carbon\Carbon::parse($data->start_date)->format('jS F Y') }}</td>
        <td>{{ \Carbon\Carbon::parse($data->end_date)->format('jS F Y') }}</td>
        <td>{{ $data->policy_code }}</td>
        <td>Cover</td>
        <td>KES {{ number_format($data->PremiumAmount) }}</td>
        <td>Chasis No</td>
      </tr>
      @php
        $totalPremiumAmount += $data->PremiumAmount; // Add the current PremiumAmount to the total
      @endphp
      @endforeach
      <tr>
          <td colspan="3">Officer Names</td>
          <td colspan="3">Date of Declatation: {{$date}}</td>

          <td colspan="2">Total Premium Amount:</td>
          <td colspan="2">KES {{ number_format($totalPremiumAmount) }}</td>
      </tr>
    </table>
  </div>
  <p class="mb-2 text-center"><I>Report generated by <b>{{ Session::get('username')}}</b>  on {{ $mytime = Carbon\Carbon::now(); }} <br>Report generated from SUCDI Insuarance System </I></p>
</body>
</html>